### ISSUE TITLE
benchmark on jsbench

### ISSUE THREAD

**Issue by jprochazk** [DavidPeicho/ecstra#17]
Hi, I talked to you on reddit the other day about the benchmarks. I put your benchmark code from [here](https://github.com/DavidPeicho/ecstra/blob/develop/benchmark/entity.bench.ts) to [jsbench](https://jsbench.me/pwklat7axw/1).

I ran into a few problems:
* The benchmark uses whatever version of your library is on NPM. For example, the `registerComponent` on `World` doesn't exist, it's named `register` instead. If you've made any significant changes since, this would influence the result greatly.
* I don't know if I did your library justice, because I had to re-write the bench code from the TS API to the JS API, and I may have made a mistake along the way.

I hope you find this useful. Feel free to close this 😃

**Comment by DavidPeicho** [comment]
Thanks a lot for this!

Yes, the benchmark has been made after the first publish. When I publish `0.0.2`, I will ensure that the benchmark also runs on jsbench!

Thanks

**Comment by DavidPeicho** [comment]
Hi, finally done [here](https://jsbench.me/6bkmt7ad7d/1).

I think some bench don't fully make sense, I have to re-work them a little!
Let me know what you think and we can maybe close this isue.
