### ISSUE TITLE
Regarding Test Coverage

### ISSUE THREAD

**Issue by aaron-harvey** [DavidPeicho/ecstra#28]
Recently I've been working on an ecsy-three type project in my free time  and there are some economic changes that would be needed in this library to improve overall support.

I was trying to add coverage to ava (in this project) but was not able to set it up as I'm far more familiar with jest/mocha. Would you accept a PR for replacing ava?  If you intend to stick with ava, do you have suggestions for coverage with typescript?

**Comment by DavidPeicho** [comment]
Hey, thanks for your issue.

I wouldn't mind to change, but first I have to be 100% sure it's worth it and there is not other solution.

In general I use mocha as well, but I had a great time using AVA on this project to be honest.

I can take a look at the coverage for AVA and if that works we can keep it

**Comment by aaron-harvey** [comment]
I liked ava as well and it's likely less work to configure it to instrument the code (below) correctly - I added the nycrc config below as well.
```
$ nyc npm run test
[...]
---------------|---------|----------|---------|---------|-------------------
File           | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
---------------|---------|----------|---------|---------|-------------------
All files      |       0 |        0 |       0 |       0 |                   
 src           |       0 |        0 |       0 |       0 |                   
  component.ts |       0 |        0 |       0 |       0 | 2-173             
  constants.ts |       0 |        0 |     100 |       0 | 1-9               
  ...rators.ts |       0 |        0 |       0 |       0 | 13-239            
  entity.ts    |       0 |        0 |       0 |       0 | 17-118            
  index.ts     |       0 |        0 |       0 |       0 |                   
  pool.ts      |       0 |        0 |       0 |       0 | 4-44              
  property.ts  |       0 |        0 |       0 |       0 | 11-300            
  query.ts     |       0 |        0 |       0 |       0 | 2-113             
  ...e-pool.ts |       0 |        0 |       0 |       0 | 4-22              
  ...-group.ts |       0 |        0 |       0 |       0 | 26-128            
  system.ts    |       0 |        0 |       0 |       0 | 17-69             
  types.ts     |       0 |        0 |       0 |       0 |                   
  utils.ts     |       0 |        0 |       0 |       0 | 11-55             
  world.ts     |       0 |        0 |       0 |       0 | 50-300            
 src/internals |       0 |        0 |       0 |       0 |                   
  archetype.ts |       0 |      100 |       0 |       0 | 3-17              
  ...anager.ts |       0 |        0 |       0 |       0 | 6-170             
  ...anager.ts |       0 |        0 |       0 |       0 | 4-82              
  queue.ts     |       0 |        0 |       0 |       0 | 6-75              
  ...anager.ts |       0 |        0 |       0 |       0 | 13-113            
---------------|---------|----------|---------|---------|-------------------
```


```
$ cat .nycrc
{
    "include": [
      "src/**/*.ts"
    ],
    "exclude": [
      "**/*.d.ts"
    ],
    "extension": [
      ".ts"
    ],
    "require": [
      "ts-node/register"
    ],
    "reporter": [
      "html",
      "text"
    ],
    "sourceMap": false,
    "instrument": true,
    "all": true
}
```

**Comment by DavidPeicho** [comment]
It doesn't really look like it works properly 😄

**Comment by aaron-harvey** [comment]
EDIT: It seems that mocha requires commonjs in tsconfig and package.json (type = module currently), which ends up breaking the examples and build script - going to keep plugging away and see if I can get it sorted

I had some time after work today and managed to get mocha + nyc set up and the coverage working 🎉 

It was a bit more complicated than I expected (compared to jest) but I did learn some things along the way.
Still need to clean up the changes to minimize the diff - should be able to get that opened tomorrow or sunday.

Also, I went with [earljs](https://earljs.dev/) in lue of chai+sinon due to the typescript support and jest like features.

![image](https://user-images.githubusercontent.com/10888871/113465498-476e3500-93e9-11eb-8498-ccfa581bc27d.png)

**Comment by DavidPeicho** [comment]
Hi, what about using [c8](https://github.com/bcoe/c8) instead of NYC just?
Haven't had a good look but it apparently uses the V8 coverage features so I guess it should be more reliable.

It seems to work well enough:

![image](https://user-images.githubusercontent.com/8783766/115105267-c28d2a80-9f55-11eb-90ef-6e0539fa5244.png)

**Comment by DavidPeicho** [comment]
I propose this because I didn't have to do anything. I simply used c8 and it worked out of the box

**Comment by DavidPeicho** [comment]
Just added c8 in #29.

If you have any issue with it or the test suite we can think about migrating the entire stack to something else.

**Comment by DavidPeicho** [comment]
You mentioned:
> there are some economic changes

Let's discuss that in other PR and how we can improve those issues?
